apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: my-nginx-app
        image: public.ecr.aws/njlaw/nginx-with-tools
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app-svc
  namespace: default
spec:
  selector:
    app: my-nginx-app
  ports:
  - port: 8082
    targetPort: 80
  type: NodePort
