apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name:  shared-volume
        mountPath:  /var/www/html
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - "while 1; do date > /tmp/shared; sleep 10; done"
    volumeMounts:
      - name:  shared-volume
        mountPath:  /tmp/shared
    
